import 'package:flutter/foundation.dart';
import '../models/sale.dart';
import '../models/item.dart';
import '../models/customer.dart';
import '../models/one_time_discount.dart';
import '../models/item_quantity_offer.dart';
import '../models/discount_request.dart';
import '../services/api_service.dart';
import '../providers/offline_provider.dart';

class SaleProvider with ChangeNotifier {
  // Cart items
  List<SaleItem> _cartItems = [];

  // Selected customer
  Customer? _selectedCustomer;

  // Payment type
  String _paymentType = 'Cash'; // Cash, Credit Card, Credit, Due

  // Multiple payments list
  List<SalePayment> _payments = [];

  // Getters
  List<SaleItem> get cartItems => _cartItems;
  Customer? get selectedCustomer => _selectedCustomer;
  String get paymentType => _paymentType;
  List<SalePayment> get payments => _payments;

  /// Lines the cashier actually added. Offer reward lines are generated by
  /// [_syncOfferFreeLine] and must be excluded from any "is this item in the
  /// cart / how many did they buy" question, otherwise a same-item reward gets
  /// counted as if it were purchased and the offer re-triggers off its own reward.
  List<SaleItem> get paidItems =>
      _cartItems.where((item) => !item.quantityOfferFree).toList();

  /// The purchased (non-reward) line for [itemId], or null if it isn't in the cart.
  SaleItem? paidItemFor(int itemId) {
    for (final item in _cartItems) {
      if (item.itemId == itemId && !item.quantityOfferFree) return item;
    }
    return null;
  }

  // Cart metrics
  int get itemCount => _cartItems.length;

  double get subtotal {
    return _cartItems.fold(0.0, (sum, item) => sum + (item.quantity * item.unitPrice));
  }

  double get totalDiscount {
    // Always use fixed discount (not percentage)
    return _cartItems.fold(0.0, (sum, item) => sum + item.discount);
  }

  double get total {
    return subtotal - totalDiscount;
  }

  bool get hasItems => _cartItems.isNotEmpty;

  // Payment metrics
  double get totalPayments {
    return _payments.fold(0.0, (sum, payment) => sum + payment.amount);
  }

  double get amountDue {
    return total - totalPayments;
  }

  bool get hasPayments => _payments.isNotEmpty;

  bool get isFullyPaid => amountDue <= 0;

  // Stock location (will be set from LocationProvider)
  int? _stockLocation;

  /// sale_id this cart was loaded from via "Resume Sale", or null for a fresh
  /// cart. Web reuses the same sale row across suspend -> resume -> suspend
  /// (Sale_lib::copy_entire_sale keeps the session on the original sale_id);
  /// the app instead deleted the suspended row the moment it was resumed and
  /// always created a brand new one on the next suspend, so one order in
  /// progress piled up as several unrelated entries in suspended history.
  /// Carrying the id here lets the next suspend update the original row
  /// instead of inserting another.
  int? _resumedFromSaleId;
  int? get resumedFromSaleId => _resumedFromSaleId;
  void setResumedFromSaleId(int? saleId) {
    _resumedFromSaleId = saleId;
  }

  // Getter for stock location
  int? get stockLocation => _stockLocation;

  // Set stock location
  void setStockLocation(int locationId) {
    final changed = _stockLocation != locationId;
    _stockLocation = locationId;
    notifyListeners();
    // Group offers are scoped to a location, so refetch when it changes
    if (changed) loadGroupOffers();
  }

  // One-time discounts tracking (itemId -> OneTimeDiscount)
  final Map<int, OneTimeDiscount> _oneTimeDiscounts = {};

  // API service instance
  final ApiService _apiService = ApiService();

  // Get one-time discount for an item
  OneTimeDiscount? getOneTimeDiscount(int itemId) {
    return _oneTimeDiscounts[itemId];
  }

  // Check if item has one-time discount applied (quantity must meet threshold)
  bool hasOneTimeDiscount(int itemId) {
    if (!_oneTimeDiscounts.containsKey(itemId)) {
      return false;
    }

    // Check if quantity meets the discount requirement
    final discount = _oneTimeDiscounts[itemId]!;
    final purchasedQty = paidItemFor(itemId)?.quantity ?? 0;

    return discount.isValidForQuantity(purchasedQty);
  }

  // Check if item has pending one-time discount (available but quantity not met)
  bool hasPendingOneTimeDiscount(int itemId) {
    if (!_oneTimeDiscounts.containsKey(itemId)) {
      return false;
    }

    // Check if quantity does NOT meet the discount requirement
    final discount = _oneTimeDiscounts[itemId]!;
    final purchasedQty = paidItemFor(itemId)?.quantity ?? 0;

    return !discount.isValidForQuantity(purchasedQty);
  }

  // Get required quantity for one-time discount
  double? getOneTimeDiscountRequiredQty(int itemId) {
    return _oneTimeDiscounts[itemId]?.quantity;
  }

  // Get all applied one-time discount IDs (for marking as used)
  /// IDs of one-time discounts that were actually applied to the cart.
  ///
  /// `_oneTimeDiscounts` holds every discount found for a cart item, including
  /// ones whose quantity condition was never met (the UI shows those as a pending
  /// "OTC: n" badge). Marking those as used would burn a customer's one-time
  /// discount without ever giving it. The web only completes discounts whose
  /// `one_time_discount_id` made it onto the cart line, i.e. applied ones.
  List<int> getAppliedDiscountIds() {
    final ids = <int>[];
    for (final entry in _oneTimeDiscounts.entries) {
      final purchasedQty = paidItemFor(entry.key)?.quantity ?? 0;
      if (entry.value.isValidForQuantity(purchasedQty)) {
        ids.add(entry.value.discountId);
      }
    }
    return ids;
  }

  // Quantity offers tracking (itemId -> ItemQuantityOffer)
  final Map<int, ItemQuantityOffer> _quantityOffers = {};

  // Get quantity offer for an item
  ItemQuantityOffer? getQuantityOffer(int itemId) {
    return _quantityOffers[itemId];
  }

  // Check if item has quantity offer
  bool hasQuantityOffer(int itemId) {
    return _quantityOffers.containsKey(itemId);
  }

  // Get all applied quantity offer data for redemption
  List<Map<String, dynamic>> getAppliedOffers() {
    final List<Map<String, dynamic>> appliedOffers = [];

    for (var entry in _quantityOffers.entries) {
      final itemId = entry.key;
      final offer = entry.value;

      // Purchased quantity comes from the paid line only -- never the reward line
      final cartItem = paidItemFor(itemId);
      if (cartItem == null || cartItem.quantity <= 0) continue;

      // Calculate the reward
      final freeQty = offer.calculateReward(cartItem.quantity);
      if (freeQty <= 0) continue;

      // Value given away is the reward item's price, which is not the purchased
      // item's price when the offer hands over a different item.
      final rewardItemId = offer.resolveRewardItemId(itemId);
      final rewardUnitPrice = offer.isCrossItemReward(itemId)
          ? (offer.rewardItemUnitPrice ?? cartItem.unitPrice)
          : cartItem.unitPrice;

      appliedOffers.add({
        'offer_id': offer.offerId,
        'item_id': itemId,
        'reward_item_id': rewardItemId,
        'purchased_quantity': cartItem.quantity,
        'reward_quantity': freeQty,
        'item_unit_price': cartItem.unitPrice,
        'total_discount_value': freeQty * rewardUnitPrice,
      });
    }

    return appliedOffers;
  }

  // Approved discount requests tracking (itemId -> CheckApprovedDiscountResponse)
  final Map<int, CheckApprovedDiscountResponse> _approvedDiscountRequests = {};

  // Get approved discount request for an item
  CheckApprovedDiscountResponse? getApprovedDiscountRequest(int itemId) {
    return _approvedDiscountRequests[itemId];
  }

  // Check if item has an approved discount request applied
  bool hasApprovedDiscountRequest(int itemId) {
    final request = _approvedDiscountRequests[itemId];
    if (request == null || !request.hasApproved) return false;

    final cartItem = _cartItems.firstWhere(
      (item) => item.itemId == itemId,
      orElse: () => SaleItem(
        itemId: itemId, itemName: '', line: 0, quantity: 0, costPrice: 0, unitPrice: 0,
      ),
    );

    // Discount is applied when quantity matches and discount is set
    return request.quantity != null && cartItem.quantity == request.quantity! && cartItem.discount > 0;
  }

  // Check if item has pending approved discount (available but not yet applied)
  // This is no longer used since discount auto-applies with forced quantity
  bool hasPendingApprovedDiscount(int itemId) {
    return false; // Discount always auto-applies now
  }

  // Check if an item's quantity is locked by an approved discount
  bool isQuantityLockedByApprovedDiscount(int itemId) {
    final request = _approvedDiscountRequests[itemId];
    if (request == null || !request.hasApproved) return false;
    final cartItem = _cartItems.firstWhere(
      (item) => item.itemId == itemId,
      orElse: () => SaleItem(
        itemId: itemId, itemName: '', line: 0, quantity: 0, costPrice: 0, unitPrice: 0,
      ),
    );
    // Locked when discount is applied (quantity matches approved quantity)
    return request.quantity != null && cartItem.quantity == request.quantity! && cartItem.discount > 0;
  }

  // Get all applied approved discount request IDs (for marking as used)
  List<int> getAppliedDiscountRequestIds() {
    final List<int> ids = [];
    for (var entry in _approvedDiscountRequests.entries) {
      final itemId = entry.key;
      final request = entry.value;
      if (request.hasApproved && request.requestId != null && hasApprovedDiscountRequest(itemId)) {
        ids.add(request.requestId!);
      }
    }
    return ids;
  }

  // Add item to cart
  void addItem(Item item, {double quantity = 1, int? locationId}) async {
    // No location fallback to a guessed default: item_location decides which
    // supervisor's suspended-sales list an item ends up filed under. A wrong
    // guess doesn't fail loudly -- it silently attaches the sale to whichever
    // stock_location_id the default happened to be, which showed up as
    // another seller's suspended sale leaking data across supervisors.
    // Left null is the honest state when the location genuinely is not
    // known yet; the server likewise must not paper over a missing value.
    final itemLocationId = locationId ?? _stockLocation;
    if (itemLocationId == null) {
      debugPrint(
          '⚠️ addItem: no stock location available for item ${item.itemId}; not adding to avoid mis-filing the sale.');
      return;
    }

    // Check if item already exists in cart. Reward lines are skipped so that
    // scanning an item that is also its own offer reward increments the paid
    // line instead of silently topping up the free one.
    final existingIndex = _cartItems
        .indexWhere((i) => i.itemId == item.itemId && !i.quantityOfferFree);

    if (existingIndex >= 0) {
      // Update quantity if item exists
      final existingItem = _cartItems[existingIndex];
      _cartItems[existingIndex] = existingItem.copyWith(
        quantity: existingItem.quantity + quantity,
      );
    } else {
      // Add new item
      final saleItem = SaleItem(
        itemId: item.itemId,
        itemName: item.name,
        line: _cartItems.length + 1,
        quantity: quantity,
        costPrice: item.costPrice,
        unitPrice: item.unitPrice,
        discount: 0,
        discountType: 1, // Fixed (changed from 0=Percentage to 1=Fixed)
        discountLimit: item.discountLimit,
        stockLocationId: itemLocationId, // Use selected location
        availableStock: item.quantity, // Store available stock for display
      );
      _cartItems.add(saleItem);
    }

    notifyListeners();

    // Check for quantity offers after adding/updating item
    await checkAndApplyQuantityOffer(item.itemId);

    // Check for one-time discounts if customer is selected
    if (_selectedCustomer != null) {
      await checkAndApplyOneTimeDiscount(item.itemId);
      // Check for approved discount requests (SADA feature)
      await checkAndApplyApprovedDiscount(item.itemId);
    }
  }

  // Add SaleItem directly to cart (used for resuming suspended sales)
  void addSaleItem(SaleItem item) {
    final saleItem = item.copyWith(line: _cartItems.length + 1);
    _cartItems.add(saleItem);
    notifyListeners();
  }

  // Update item quantity
  void updateQuantity(int index, double quantity) async {
    if (index >= 0 && index < _cartItems.length) {
      if (quantity <= 0) {
        removeItem(index);
      } else {
        final itemId = _cartItems[index].itemId;
        final oldItem = _cartItems[index];

        // Reward lines are derived from the paid line's quantity; editing them
        // directly would be overwritten on the next offer sync anyway.
        if (oldItem.quantityOfferFree) {
          return;
        }

        // Prevent quantity change if locked by approved discount
        if (isQuantityLockedByApprovedDiscount(itemId)) {
          return;
        }

        // Preserve discount: recalculate total discount based on new quantity
        // Discount is stored as total (discount per item × quantity)
        double newDiscount = oldItem.discount;
        if (oldItem.discount > 0 && oldItem.quantity > 0 && oldItem.discountType == 1) {
          // Fixed discount per item - recalculate for new quantity
          final discountPerItem = oldItem.discount / oldItem.quantity;
          newDiscount = discountPerItem * quantity;
        }

        _cartItems[index] = oldItem.copyWith(
          quantity: quantity,
          discount: newDiscount,
        );
        notifyListeners();

        // Check for quantity offers after updating quantity
        await checkAndApplyQuantityOffer(itemId);

        // Check for one-time discounts if customer is selected
        if (_selectedCustomer != null) {
          await checkAndApplyOneTimeDiscount(itemId);
          await checkAndApplyApprovedDiscount(itemId);
        }
      }
    }
  }

  // Update item price
  void updatePrice(int index, double price) {
    if (index >= 0 && index < _cartItems.length) {
      _cartItems[index] = _cartItems[index].copyWith(unitPrice: price);
      notifyListeners();
    }
  }

  // Update item discount
  void updateDiscount(int index, double discount, {int discountType = 1}) {
    if (index >= 0 && index < _cartItems.length) {
      _cartItems[index] = _cartItems[index].copyWith(
        discount: discount,
        discountType: discountType,
      );
      notifyListeners();
    }
  }

  // Remove item from cart
  void removeItem(int index) {
    if (index >= 0 && index < _cartItems.length) {
      final removed = _cartItems[index];
      final itemId = removed.itemId;
      _cartItems.removeAt(index);

      if (removed.quantityOfferFree) {
        // Removing a reward line on its own: drop the offer so it does not get
        // re-added on the next sync. The cashier has explicitly declined it.
        _quantityOffers.removeWhere((_, offer) => offer.offerId == removed.quantityOfferId);
      } else {
        // Remove associated one-time discount, quantity offer, and approved discount request
        _oneTimeDiscounts.remove(itemId);
        final offer = _quantityOffers.remove(itemId);
        // The reward line has no owner any more, so it must go too
        if (offer != null) {
          _cartItems.removeWhere(
            (item) => item.quantityOfferFree && item.quantityOfferId == offer.offerId,
          );
        }
        _approvedDiscountRequests.remove(itemId);
      }

      _renumberLines();
      _syncGroupOfferLines();
      notifyListeners();
    }
  }

  /// Keep `line` contiguous and 1-based after any structural cart change.
  void _renumberLines() {
    for (int i = 0; i < _cartItems.length; i++) {
      _cartItems[i] = _cartItems[i].copyWith(line: i + 1);
    }
  }

  /// Line number of the purchased item whose offer produced reward line [offerId].
  int? _parentLineForOffer(int? offerId) {
    if (offerId == null) return null;
    for (final entry in _quantityOffers.entries) {
      if (entry.value.offerId == offerId) {
        return paidItemFor(entry.key)?.line;
      }
    }
    return null;
  }

  // Clear cart
  void clearCart() {
    _cartItems.clear();
    _selectedCustomer = null;
    _payments.clear();
    _oneTimeDiscounts.clear();
    _quantityOffers.clear();
    _approvedDiscountRequests.clear();
    _resumedFromSaleId = null;
    notifyListeners();
  }

  /// Full reset for a login/logout boundary.
  ///
  /// SaleProvider is a single instance for the app's whole process (created
  /// once in main.dart), so on a shared device it survives a logout. clearCart
  /// never touched _stockLocation, so the previous person's location quietly
  /// stayed live: the next seller's first addItem(), before their own location
  /// finished loading, filed the item under a stranger's stock_location_id --
  /// a suspended sale would then read back scoped to someone else's location
  /// entirely, invisible to its actual owner.
  void resetForNewUser() {
    _stockLocation = null;
    clearCart();
  }

  // Check and apply one-time discount for an item
  Future<bool> checkAndApplyOneTimeDiscount(int itemId, {String? date}) async {
    // Must have customer and stock location
    if (_selectedCustomer == null || _stockLocation == null) {
      debugPrint('OneTimeDiscount: Skipped - customer=${_selectedCustomer?.personId}, location=$_stockLocation');
      return false;
    }

    try {
      debugPrint('OneTimeDiscount: Checking item=$itemId, customer=${_selectedCustomer!.personId}, location=$_stockLocation');
      final response = await _apiService.checkOneTimeDiscount(
        customerId: _selectedCustomer!.personId,
        itemId: itemId,
        locationId: _stockLocation!,
        date: date,
      );

      debugPrint('OneTimeDiscount: API response success=${response.isSuccess}, available=${response.data?.available}');

      if (response.isSuccess && response.data != null && response.data!.available) {
        final discount = response.data!.discount;
        if (discount != null) {
          debugPrint('OneTimeDiscount: Found discount amount=${discount.discountAmount}, requiredQty=${discount.quantity}');
          // Store the discount info (for reference even if not yet applicable)
          _oneTimeDiscounts[itemId] = discount;

          // Find the purchased line in cart -- never an offer reward line, which
          // can share the same item id but must stay at zero price
          final index = _cartItems
              .indexWhere((item) => item.itemId == itemId && !item.quantityOfferFree);
          if (index >= 0) {
            final item = _cartItems[index];
            debugPrint('OneTimeDiscount: Cart item qty=${item.quantity}, required=${discount.quantity}');

            // Only apply discount if quantity meets the required threshold
            if (discount.isValidForQuantity(item.quantity)) {
              // Calculate total discount for the quantity
              final totalDiscount = discount.getTotalDiscountAmount(item.quantity);
              debugPrint('OneTimeDiscount: Applying totalDiscount=$totalDiscount');

              // Apply as fixed discount
              _cartItems[index] = item.copyWith(
                discount: totalDiscount,
                discountType: 1, // Fixed
              );
              notifyListeners();
              return true;
            } else {
              debugPrint('OneTimeDiscount: Quantity not met - cart=${item.quantity}, required=${discount.quantity}');
              // Quantity not sufficient - clear any existing discount
              if (item.discount > 0) {
                _cartItems[index] = item.copyWith(
                  discount: 0.0,
                  discountType: 1, // Fixed
                );
                notifyListeners();
              }
              return false;
            }
          }
        }
      } else {
        debugPrint('OneTimeDiscount: No discount available - ${response.message}');
      }
      return false;
    } catch (e) {
      debugPrint('OneTimeDiscount: Error - $e');
      return false;
    }
  }

  // Check for one-time discounts for all items in cart
  Future<void> checkAllOneTimeDiscounts({String? date}) async {
    if (_selectedCustomer == null || _stockLocation == null) {
      return;
    }

    for (var item in _cartItems) {
      await checkAndApplyOneTimeDiscount(item.itemId, date: date);
    }
  }

  // Check and apply approved discount request for an item
  Future<bool> checkAndApplyApprovedDiscount(int itemId) async {
    // Must have customer selected and feature enabled
    if (_selectedCustomer == null) return false;

    // Check if discount requests feature is enabled for this client
    final hasFeature = ApiService.currentClient?.features.hasDiscountRequests ?? false;
    if (!hasFeature) return false;

    try {
      final response = await _apiService.checkApprovedDiscount(
        customerId: _selectedCustomer!.personId,
        itemId: itemId,
      );

      if (response.isSuccess && response.data != null && response.data!.hasApproved) {
        final approved = response.data!;
        _approvedDiscountRequests[itemId] = approved;

        debugPrint('ApprovedDiscount: itemId=$itemId, approved qty=${approved.quantity}, discount=${approved.discount}, requestId=${approved.requestId}');

        // Find the purchased line in cart, skipping offer reward lines
        final index = _cartItems
            .indexWhere((item) => item.itemId == itemId && !item.quantityOfferFree);
        if (index >= 0) {
          final item = _cartItems[index];

          // Apply discount and lock quantity to approved amount
          if (approved.quantity != null && approved.quantity! > 0) {
            // Set quantity to exactly the approved quantity and apply discount
            final approvedQty = approved.quantity!;
            final totalDiscount = (approved.discount ?? 0) * approvedQty;
            debugPrint('ApprovedDiscount: Setting cart qty=$approvedQty, totalDiscount=$totalDiscount (was qty=${item.quantity})');
            _cartItems[index] = item.copyWith(
              quantity: approvedQty,
              discount: totalDiscount,
              discountType: 1, // Fixed
            );
            notifyListeners();
            return true;
          } else {
            // Quantity not met - clear discount if previously applied
            if (item.discount > 0 && _approvedDiscountRequests.containsKey(itemId)) {
              _cartItems[index] = item.copyWith(
                discount: 0.0,
                discountType: 1,
              );
              notifyListeners();
            }
            return false;
          }
        }
      } else {
        // No approved discount - remove tracking if existed
        _approvedDiscountRequests.remove(itemId);
      }
      return false;
    } catch (e) {
      debugPrint('ApprovedDiscount: Error - $e');
      return false;
    }
  }

  // Check for approved discount requests for all items in cart
  Future<void> checkAllApprovedDiscounts() async {
    if (_selectedCustomer == null) return;

    final hasFeature = ApiService.currentClient?.features.hasDiscountRequests ?? false;
    if (!hasFeature) return;

    for (var item in _cartItems) {
      await checkAndApplyApprovedDiscount(item.itemId);
    }
  }

  // Mark all used one-time discounts (call after sale completion)
  Future<void> markDiscountsAsUsed(int saleId) async {
    final discountIds = getAppliedDiscountIds();
    debugPrint('markDiscountsAsUsed: sale_id=$saleId, discountIds=$discountIds');

    for (var discountId in discountIds) {
      try {
        debugPrint('markDiscountsAsUsed: Calling API for discount_id=$discountId');
        final response = await _apiService.useOneTimeDiscount(
          discountId: discountId,
          saleId: saleId,
        );
        debugPrint('markDiscountsAsUsed: API response success=${response.isSuccess}, message=${response.message}');
      } catch (e) {
        debugPrint('markDiscountsAsUsed: Error marking discount $discountId as used: $e');
      }
    }
  }

  // Check and apply quantity offer for an item
  Future<bool> checkAndApplyQuantityOffer(int itemId, {String? date}) async {
    // Must have stock location
    if (_stockLocation == null) {
      return false;
    }

    try {
      final response = await _apiService.checkQuantityOffer(
        itemId: itemId,
        locationId: _stockLocation!,
        customerId: _selectedCustomer?.personId,
        date: date,
      );

      if (response.isSuccess && response.data != null && response.data!.available) {
        final offer = response.data!.offer;
        if (offer != null) {
          // Store the offer info
          _quantityOffers[itemId] = offer;

          // Materialise (or update) the free line for this offer
          _syncOfferFreeLine(itemId);
          _syncGroupOfferLines();

          // Notify listeners to update UI
          notifyListeners();
          return true;
        }
      }

      // No offer available any more -- drop it and any reward line it left behind
      final stale = _quantityOffers.remove(itemId);
      if (stale != null) {
        _removeOfferFreeLines(stale.offerId);
        _renumberLines();
        notifyListeners();
      }
      // A group offer may still apply even when this item has no single-item one
      _syncGroupOfferLines();
      return false;
    } catch (e) {
      debugPrint('Error checking quantity offer: $e');
      return false;
    }
  }

  // Check for quantity offers for all items in cart
  Future<void> checkAllQuantityOffers({String? date}) async {
    if (_stockLocation == null) {
      return;
    }

    // Snapshot the paid item ids: _cartItems is mutated as reward lines appear
    final itemIds = paidItems.map((item) => item.itemId).toList();
    for (final itemId in itemIds) {
      await checkAndApplyQuantityOffer(itemId, date: date);
    }
  }

  // ---------------------------------------------------------------------
  // Group offers
  //
  // A group offer's threshold is the COMBINED quantity of several items, so it
  // cannot be checked per item the way single-item offers are. The active group
  // offers are fetched once for the location/customer and then evaluated
  // locally against the cart, matching Sale_lib on the web.
  //
  // Only the badge is computed here. api/Sales.php still creates the free line
  // and records the redemption when the sale is saved, exactly as it does for
  // single-item offers.
  // ---------------------------------------------------------------------

  List<ItemQuantityOffer> _groupOffers = [];
  List<ItemQuantityOffer> get groupOffers => _groupOffers;

  /// Cart quantities keyed by item id, ignoring reward lines.
  Map<int, double> get _paidQuantities {
    final map = <int, double>{};
    for (final item in _cartItems) {
      if (item.quantityOfferFree) continue;
      map[item.itemId] = (map[item.itemId] ?? 0) + item.quantity;
    }
    return map;
  }

  Future<void> loadGroupOffers({String? date}) async {
    if (_stockLocation == null) return;

    try {
      final response = await _apiService.getGroupOffers(
        locationId: _stockLocation!,
        customerId: _selectedCustomer?.personId,
        date: date,
      );

      if (response.isSuccess && response.data != null) {
        _groupOffers = response.data!.offers;
        debugPrint('GroupOffers: loaded ${_groupOffers.length}');
        _syncGroupOfferLines();
        notifyListeners();
      }
    } catch (e) {
      debugPrint('GroupOffers: failed to load - $e');
    }
  }

  /// The highest-priority group offer that [itemId] belongs to, or null.
  ///
  /// The API returns them ordered by priority, so the first match wins -- the
  /// same rule the server applies.
  ItemQuantityOffer? getGroupOfferForItem(int itemId) {
    for (final offer in _groupOffers) {
      if (offer.groupItemIds.contains(itemId)) return offer;
    }
    return null;
  }

  /// Combined quantity of [offer]'s member items currently in the cart.
  double groupOfferCombinedQuantity(ItemQuantityOffer offer) =>
      offer.combinedQuantity(_paidQuantities);

  /// Free quantity this group offer currently earns, 0 when below threshold.
  double groupOfferReward(ItemQuantityOffer offer) =>
      offer.calculateReward(groupOfferCombinedQuantity(offer));

  /// Item the group offer would hand over, given what is in the cart.
  int groupOfferRewardItemId(ItemQuantityOffer offer) =>
      offer.resolveGroupRewardItemId(_paidQuantities);

  /// True when [item] is a reward line produced by a GROUP offer.
  ///
  /// Matters at submission time: api/Sales.php regenerates single-item reward
  /// lines server-side, but has no group-offer handling at all, so group reward
  /// lines have to be sent or the customer never receives them.
  bool isGroupOfferLine(SaleItem item) {
    if (!item.quantityOfferFree || item.quantityOfferId == null) return false;
    return _groupOffers.any((offer) => offer.offerId == item.quantityOfferId);
  }

  /// Add, update or remove the reward line for every active group offer.
  ///
  /// Mirrors Sale_lib::_check_and_apply_group_offers() on the web, which is what
  /// puts the free line in the web cart.
  void _syncGroupOfferLines() {
    if (_groupOffers.isEmpty) return;

    var changed = false;

    for (final offer in _groupOffers) {
      final freeQty = groupOfferReward(offer);
      final existingIndex = _cartItems.indexWhere(
        (item) => item.quantityOfferFree && item.quantityOfferId == offer.offerId,
      );

      // Below threshold, or no member of the group is in the cart any more
      final anyMemberInCart =
          offer.groupItemIds.any((id) => paidItemFor(id) != null);

      if (freeQty <= 0 || !anyMemberInCart) {
        if (existingIndex >= 0) {
          _cartItems.removeAt(existingIndex);
          changed = true;
        }
        continue;
      }

      final rewardItemId = groupOfferRewardItemId(offer);
      final source = paidItemFor(rewardItemId) ??
          offer.groupItemIds
              .map(paidItemFor)
              .firstWhere((item) => item != null, orElse: () => null);
      if (source == null) continue;

      final rewardName = rewardItemId == source.itemId
          ? source.itemName
          : (offer.rewardItemName ?? source.itemName);

      if (existingIndex >= 0) {
        final existing = _cartItems[existingIndex];
        if (existing.quantity == freeQty && existing.itemId == rewardItemId) {
          continue;
        }
        _cartItems[existingIndex] = existing.copyWith(
          itemId: rewardItemId,
          itemName: rewardName,
          quantity: freeQty,
        );
        changed = true;
      } else {
        _cartItems.add(SaleItem(
          itemId: rewardItemId,
          itemName: rewardName,
          line: _cartItems.length + 1,
          quantity: freeQty,
          costPrice: rewardItemId == source.itemId
              ? source.costPrice
              : (offer.rewardItemCostPrice ?? 0),
          unitPrice: 0, // FREE
          discount: 0,
          discountType: 1,
          description: '🎁 OFFER: ${offer.offerName}'
              '${offer.offerCode != null && offer.offerCode!.isNotEmpty ? ' (${offer.offerCode})' : ''}',
          stockLocationId: source.stockLocationId ?? _stockLocation,
          quantityOfferFree: true,
          quantityOfferId: offer.offerId,
        ));
        changed = true;
      }
    }

    if (changed) {
      _renumberLines();
      notifyListeners();
    }
  }

  /// Remove every reward line belonging to [offerId].
  void _removeOfferFreeLines(int offerId) {
    _cartItems.removeWhere(
      (item) => item.quantityOfferFree && item.quantityOfferId == offerId,
    );
  }

  /// Bring the cart's reward line for [itemId]'s offer in line with the quantity
  /// currently purchased.
  ///
  /// This mirrors `Sale_lib::_apply_quantity_offer()` on the web: the reward is a
  /// real zero-priced cart line, not just a badge, so it prints on the receipt and
  /// is deducted from stock when the sale is saved.
  void _syncOfferFreeLine(int itemId) {
    final offer = _quantityOffers[itemId];
    final paidItem = paidItemFor(itemId);

    if (offer == null || paidItem == null) {
      if (offer != null) _removeOfferFreeLines(offer.offerId);
      _renumberLines();
      return;
    }

    final freeQty = offer.calculateReward(paidItem.quantity);
    final rewardItemId = offer.resolveRewardItemId(itemId);

    // Below the threshold: no reward line at all
    if (freeQty <= 0) {
      _removeOfferFreeLines(offer.offerId);
      _renumberLines();
      return;
    }

    final existingIndex = _cartItems.indexWhere(
      (item) => item.quantityOfferFree && item.quantityOfferId == offer.offerId,
    );

    if (existingIndex >= 0) {
      final existing = _cartItems[existingIndex];
      // Nothing changed -- avoid a pointless list write
      if (existing.quantity == freeQty && existing.itemId == rewardItemId) {
        return;
      }
      _cartItems[existingIndex] = existing.copyWith(
        itemId: rewardItemId,
        itemName: _rewardItemName(offer, paidItem, rewardItemId),
        quantity: freeQty,
        costPrice: _rewardCostPrice(offer, paidItem, rewardItemId),
      );
      _renumberLines();
      return;
    }

    _cartItems.add(SaleItem(
      itemId: rewardItemId,
      itemName: _rewardItemName(offer, paidItem, rewardItemId),
      line: _cartItems.length + 1,
      quantity: freeQty,
      costPrice: _rewardCostPrice(offer, paidItem, rewardItemId),
      unitPrice: 0, // FREE
      discount: 0,
      discountType: 1,
      description: _offerLineDescription(offer, paidItem, rewardItemId),
      stockLocationId: paidItem.stockLocationId ?? _stockLocation,
      quantityOfferFree: true,
      quantityOfferId: offer.offerId,
    ));
    _renumberLines();
  }

  String _rewardItemName(ItemQuantityOffer offer, SaleItem paidItem, int rewardItemId) {
    if (rewardItemId == paidItem.itemId) return paidItem.itemName;
    return offer.rewardItemName ?? 'Item #$rewardItemId';
  }

  double _rewardCostPrice(ItemQuantityOffer offer, SaleItem paidItem, int rewardItemId) {
    if (rewardItemId == paidItem.itemId) return paidItem.costPrice;
    return offer.rewardItemCostPrice ?? 0;
  }

  /// Matches the web's free-line label so receipts read the same on both channels.
  String _offerLineDescription(ItemQuantityOffer offer, SaleItem paidItem, int rewardItemId) {
    final buffer = StringBuffer('🎁 OFFER: ${offer.offerName}');
    if (offer.offerCode != null && offer.offerCode!.isNotEmpty) {
      buffer.write(' (${offer.offerCode})');
    }
    if (rewardItemId != paidItem.itemId) {
      buffer.write(' [Free: ${_rewardItemName(offer, paidItem, rewardItemId)}]');
    }
    return buffer.toString();
  }

  // Mark all quantity offers as redeemed (call after sale completion)
  Future<void> markOffersAsRedeemed(int saleId) async {
    final appliedOffers = getAppliedOffers();

    for (var offerData in appliedOffers) {
      try {
        await _apiService.redeemOffer(
          offerId: offerData['offer_id'],
          saleId: saleId,
          itemId: offerData['item_id'],
          rewardItemId: offerData['reward_item_id'],
          locationId: _stockLocation!,
          customerId: _selectedCustomer?.personId,
          purchasedQuantity: offerData['purchased_quantity'],
          rewardQuantity: offerData['reward_quantity'],
          itemUnitPrice: offerData['item_unit_price'],
          totalDiscountValue: offerData['total_discount_value'],
        );
      } catch (e) {
        debugPrint('Error redeeming offer ${offerData['offer_id']}: $e');
      }
    }
  }

  // Set customer
  void setCustomer(Customer? customer) {
    _selectedCustomer = customer;
    notifyListeners();
    // Exclusions are per customer, so the eligible group offers can change
    loadGroupOffers();
  }

  // Remove the selected customer (keeps the cart items).
  // Also clears customer-scoped discount/offer state so the previous customer's
  // discounts don't leak onto a subsequently selected customer.
  void clearCustomer() {
    _selectedCustomer = null;
    _oneTimeDiscounts.clear();
    _approvedDiscountRequests.clear();
    notifyListeners();
  }

  // Set payment type
  void setPaymentType(String type) {
    _paymentType = type;
    notifyListeners();
  }

  // Payment management methods
  void addPayment(SalePayment payment) {
    _payments.add(payment);
    notifyListeners();
  }

  void removePayment(int index) {
    if (index >= 0 && index < _payments.length) {
      _payments.removeAt(index);
      notifyListeners();
    }
  }

  void clearPayments() {
    _payments.clear();
    notifyListeners();
  }

  // Create sale from cart
  Sale createSale({
    List<SalePayment>? payments,
    String? comment,
    int saleType = 0,
  }) {
    return Sale(
      saleTime: DateTime.now().toIso8601String(),
      customerId: _selectedCustomer?.personId,
      employeeId: 0, // Will be set from auth provider
      comment: comment,
      saleStatus: 0, // Completed
      saleType: saleType,
      // Mirrors what the offline path already stores locally, so an online sale
      // and a synced one land on the same location server-side.
      stockLocationId: _stockLocation,
      subtotal: subtotal,
      taxTotal: 0,
      total: total,
      // Single-item reward lines are display-only: api/Sales.php regenerates
      // them server-side (zero-priced line, inventory deduction, inventory log,
      // redemption), so sending ours would duplicate the free item and deduct
      // stock twice. Group offers get NO server-side handling at all, so those
      // reward lines must be sent or the customer never receives them.
      items: _cartItems
          .where((item) => !item.quantityOfferFree || isGroupOfferLine(item))
          .toList(),
      payments: payments ?? _payments, // Use accumulated payments if not provided
    );
  }

  // Load suspended sale
  void loadSuspendedSale(Sale sale) {
    _cartItems = sale.items ?? [];
    _selectedCustomer = null; // Customer info is in the sale object
    notifyListeners();
  }

  // Get item by ID from cart
  SaleItem? getItemById(int itemId) {
    try {
      return _cartItems.firstWhere((item) => item.itemId == itemId);
    } catch (e) {
      return null;
    }
  }

  // Check if item is in cart
  bool isInCart(int itemId) {
    return _cartItems.any((item) => item.itemId == itemId);
  }

  // Get cart item count for specific item
  double getItemQuantity(int itemId) {
    final item = getItemById(itemId);
    return item?.quantity ?? 0;
  }

  // Increment item quantity
  void incrementQuantity(int index) {
    if (index >= 0 && index < _cartItems.length) {
      final currentQty = _cartItems[index].quantity;
      updateQuantity(index, currentQty + 1);
    }
  }

  // Decrement item quantity
  void decrementQuantity(int index) {
    if (index >= 0 && index < _cartItems.length) {
      final currentQty = _cartItems[index].quantity;
      updateQuantity(index, currentQty - 1);
    }
  }

  // Quick add item with default quantity
  void quickAddItem(Item item) {
    addItem(item, quantity: 1);
  }

  // Validate cart before checkout
  String? validateCart() {
    if (_cartItems.isEmpty) {
      return 'Cart is empty. Add items to continue.';
    }

    // Check for items with zero or negative quantity
    for (var item in _cartItems) {
      if (item.quantity <= 0) {
        return 'Item "${item.itemName}" has invalid quantity.';
      }
      if (item.unitPrice < 0) {
        return 'Item "${item.itemName}" has invalid price.';
      }
    }

    return null; // Valid
  }

  // Get cart summary
  Map<String, dynamic> getCartSummary() {
    return {
      'item_count': itemCount,
      'total_items': _cartItems.fold<double>(0, (sum, item) => sum + item.quantity),
      'subtotal': subtotal,
      'discount': totalDiscount,
      'total': total,
      'customer': _selectedCustomer?.fullName ?? 'Walk-in',
    };
  }

  // Apply fixed discount to entire cart
  void applyCartDiscount(double discountAmount) {
    for (int i = 0; i < _cartItems.length; i++) {
      _cartItems[i] = _cartItems[i].copyWith(
        discount: discountAmount,
        discountType: 1, // Fixed
      );
    }
    notifyListeners();
  }

  // Remove discount from cart
  void removeCartDiscount() {
    for (int i = 0; i < _cartItems.length; i++) {
      _cartItems[i] = _cartItems[i].copyWith(discount: 0);
    }
    notifyListeners();
  }

  /// Submit sale - handles both online and offline scenarios
  /// Returns a SaleSubmitResult with sale info and offline status
  Future<SaleSubmitResult> submitSale({
    required OfflineProvider offlineProvider,
    required int employeeId,
    String? comment,
    int saleType = 0,
  }) async {
    // Create sale
    final sale = Sale(
      saleTime: DateTime.now().toIso8601String(),
      customerId: _selectedCustomer?.personId,
      employeeId: employeeId,
      comment: comment,
      saleStatus: 0,
      saleType: saleType,
      subtotal: subtotal,
      taxTotal: 0,
      total: total,
      items: _cartItems,
      payments: _payments,
    );

    // Check if online
    if (offlineProvider.isOnline) {
      // Online - submit to API
      try {
        final response = await _apiService.createSale(sale);
        if (response.isSuccess && response.data != null) {
          return SaleSubmitResult(
            success: true,
            isOffline: false,
            saleId: response.data!.saleId,
            message: 'Sale completed successfully',
          );
        } else {
          // API failed, try to save offline
          return await _saveOfflineSale(sale, offlineProvider, employeeId);
        }
      } catch (e) {
        // Network error, save offline
        debugPrint('SaleProvider: Online sale failed, saving offline - $e');
        return await _saveOfflineSale(sale, offlineProvider, employeeId);
      }
    } else {
      // Offline - save locally
      return await _saveOfflineSale(sale, offlineProvider, employeeId);
    }
  }

  /// Save sale to local database when offline
  Future<SaleSubmitResult> _saveOfflineSale(
    Sale sale,
    OfflineProvider offlineProvider,
    int employeeId,
  ) async {
    final database = offlineProvider.database;
    if (database == null) {
      return SaleSubmitResult(
        success: false,
        isOffline: true,
        message: 'Offline database not initialized',
      );
    }

    try {
      // Create sale data map
      final saleData = {
        'customer_id': _selectedCustomer?.personId,
        'employee_id': employeeId,
        'sale_type': sale.saleType,
        'sale_status': 0,
        'sale_time': sale.saleTime,
        'stock_location_id': _stockLocation,
        'comment': sale.comment,
        'subtotal': subtotal,
        'tax_total': 0,
        'total': total,
        'amount_tendered': _payments.fold<double>(0, (sum, p) => sum + p.amount),
        'amount_change': 0,
      };

      // Convert sale items to local format
      final items = _cartItems.map((item) {
        // A reward line belongs to whichever paid line triggered its offer. Resolving
        // it here (rather than storing it) keeps parent_line correct after the cart is
        // renumbered by an insert or removal.
        final parentLine = item.quantityOfferFree
            ? _parentLineForOffer(item.quantityOfferId)
            : item.parentLine;

        return {
          'item_id': item.itemId,
          'item_name': item.itemName,
          'item_cost_price': item.costPrice,
          'item_unit_price': item.unitPrice,
          'quantity_purchased': item.quantity,
          'discount': item.discount,
          'discount_type': item.discountType,
          'discount_limit': item.discountLimit,
          'item_location': item.stockLocationId ?? _stockLocation,
          'serialnumber': item.serialNumber,
          // Discounts are keyed by the purchased item, never by a reward line
          'one_time_discount_id':
              item.quantityOfferFree ? null : _oneTimeDiscounts[item.itemId]?.discountId,
          'approved_request_id':
              item.quantityOfferFree ? null : _approvedDiscountRequests[item.itemId]?.requestId,
          'quantity_offer_id': item.quantityOfferId,
          'quantity_offer_free': item.quantityOfferFree ? 1 : 0,
          'parent_line': parentLine,
        };
      }).toList();

      // Convert payments to local format
      final payments = _payments.map((payment) {
        return {
          'payment_type': payment.paymentType,
          'payment_amount': payment.amount,
        };
      }).toList();

      // Create local sale with all details
      final localSaleId = await database.createLocalSale(saleData, items, payments);

      // Mark one-time discounts as used locally
      for (final discountId in getAppliedDiscountIds()) {
        await database.markOneTimeDiscountUsed(discountId, localSaleId);
      }

      return SaleSubmitResult(
        success: true,
        isOffline: true,
        localSaleId: localSaleId,
        message: 'Sale saved offline. Will sync when online.',
      );
    } catch (e) {
      debugPrint('SaleProvider: Failed to save offline sale - $e');
      return SaleSubmitResult(
        success: false,
        isOffline: true,
        message: 'Failed to save sale offline: $e',
      );
    }
  }

  /// Mark discounts as used locally (for offline sales)
  Future<void> markDiscountsAsUsedLocally(int localSaleId, OfflineProvider offlineProvider) async {
    final database = offlineProvider.database;
    if (database == null) return;

    for (final discountId in getAppliedDiscountIds()) {
      try {
        await database.markOneTimeDiscountUsed(discountId, localSaleId);
        debugPrint('SaleProvider: Marked discount $discountId as used locally');
      } catch (e) {
        debugPrint('SaleProvider: Failed to mark discount as used locally - $e');
      }
    }
  }
}

/// Result of a sale submission (online or offline)
class SaleSubmitResult {
  final bool success;
  final bool isOffline;
  final int? saleId;
  final int? localSaleId;
  final String message;

  SaleSubmitResult({
    required this.success,
    required this.isOffline,
    this.saleId,
    this.localSaleId,
    required this.message,
  });

  /// Get display sale ID (server or local)
  int? get displaySaleId => saleId ?? localSaleId;
}
