"""Regenerate lib/l10n/sw_strings.dart from tool/sw_strings.json.

sw_strings.json maps an English source string (exactly as it appears in the
Dart code, with every interpolation written as {}) to its Kiswahili text.
A key containing {} becomes a template; the {} placeholders in the Kiswahili
text are filled in order, or by number ({2}) to reorder.

    python tool/build_sw.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'sw_strings.json')
OUT = os.path.join(HERE, '..', 'lib', 'l10n', 'sw_strings.dart')


def dart(s):
    return "'" + (s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$')
                  .replace('\n', '\\n').replace('\r', '\\r')) + "'"


def main():
    data = json.load(open(SRC, encoding='utf-8'))
    extra = os.path.join(HERE, 'sw_extra.json')
    if os.path.exists(extra):
        data.update(json.load(open(extra, encoding='utf-8')))
    exact, tpl = {}, {}
    for k, v in sorted(data.items()):
        if not v or v == k:
            continue
        if '{}' in k:
            n_src = k.count('{}')
            n_dst = len(re.findall(r'\{\d*\}', v))
            if n_dst > n_src:
                print('WARN placeholders', repr(k), '->', repr(v))
            tpl[k] = v
        else:
            exact[k] = v
    lines = ['// Kiswahili translations. GENERATED by tool/build_sw.py from tool/sw_strings.json.',
             '// Do not edit by hand.', '',
             '// ignore_for_file: prefer_single_quote_strings', '']
    lines.append('const Map<String, String> kSwExact = {')
    for k, v in exact.items():
        lines.append('  %s: %s,' % (dart(k), dart(v)))
    lines.append('};')
    lines.append('')
    lines.append('const Map<String, String> kSwTemplates = {')
    for k, v in tpl.items():
        lines.append('  %s: %s,' % (dart(k), dart(v)))
    lines.append('};')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')
    print(len(exact), 'exact,', len(tpl), 'templates ->', os.path.normpath(OUT))


main()
